### ISSUE TITLE
Add xUnit unit tests to the project

### ISSUE THREAD

**Issue by Tillman32** [Tillman32/CleanArchitecture#2]
The project needs to be unit tested. Would like to try out xUnit and add a new high level test directory for the project.

**Comment by kameko** [comment]
Curious about why you're not selecting NUnit, wouldn't it make more sense since it comes standard with the dotnet toolchain?

**Comment by Tillman32** [comment]
@kameko Hey there!

Good question, although I haven't used XUnit yet... here are some of my motivational factors for checking it out:

- Its used internally by Microsoft to test .Net Core itself (over MSTest & NUnit).
- Created by the original authors of NUnit and meant to be more flexible and improves on area's lacking in the other frameworks.
- I like trying new things.

Some interesting articles around the topic:

[https://dev.to/hatsrumandcode/net-core-2-why-xunit-and-not-nunit-or-mstest--aei](https://dev.to/hatsrumandcode/net-core-2-why-xunit-and-not-nunit-or-mstest--aei)
[https://visualstudiomagazine.com/articles/2018/11/01/net-core-testing.aspx](https://visualstudiomagazine.com/articles/2018/11/01/net-core-testing.aspx)

I'm not quite sure what you mean by it coming standard however, its piecemeal - you include the package for whichever test framework you want to use. Could you elaborate?

**Comment by kameko** [comment]
Interesting! Sorry, just meant that the `dotnet new` command has presets for NUnit, that was my only reasoning. I'm interesting in trying xUnit out too, now.

**Comment by Tillman32** [comment]
@kameko no worries! Let me know if you do end up testing it out, how you like it, etc. 👍

**Comment by MBakirci** [comment]
#5
