### ISSUE TITLE
Replace ArticleCategoryDTO with ArticleCategoryEntity inside ArticleEntity

### ISSUE THREAD

**Issue by antoniovalentini** [Tillman32/CleanArchitecture#3]
You included a **ArticleCategoryDTO** property inside the ArticleEntity, instead of **ArticleCategoryEntity**.
```C#
public virtual ArticleCategoryDTO Category { get; set; }
```

I suppose it to be a typo, because this way an article is referencing a category dto without the datetime. You end up with 3 tables this way:
- Articles
- ArticleCategories
- ArticleCategoryDTO

**Comment by Tillman32** [comment]
@antoniovalentini Good eye, thanks for catching this. It should be the entity that is referenced, I'll get it updated. Appreciate it!
